apiVersion: v1
kind: Namespace
metadata:
  name: anchore-lab
  labels:
    purpose: lab-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: anchore-lab-system
  labels:
    purpose: platform-services
